Programs/toDo_app/home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('new_todo', views.new_todo, name="new_todo"),
    path("delete_todo/<id>", views.delete_todo, name="delete_todo"),
]

Programs/toDo_app/toDo_app/urls.py
from django.contrib import admin
from django.urls import path, include
#import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("home.urls","home"),namespace="home")),
]

Programs/toDo_app/home/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):
	text = models.TextField()
	date_added = models.DateField(auto_now_add = True)
	class Meta:
		verbose_name_plural = "Entries"
	def __str__(self):
		return self.text

Programs/toDo_app/home/forms.py
from django import forms

from .models import Entry

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ["text"]
		labels = {"text": ""}

Programs/toDo_app/home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Entry
from .forms import EntryForm
# Create your views here.


def index(request):
	toDo = Entry.objects.all().order_by('-id')

	context = {"toDo":toDo}
	return render(request,"index.html",context)

def new_todo(request):
	if request.method != "POST":
		form = EntryForm()
	else:
		form = EntryForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect("/")

	context = {"form":form}
	return render(request, "new_todo.html", context)

def delete_todo(request,id):
	Entry.objects.filter(id=id).delete()
	return HttpResponseRedirect("/")

Programs/toDo_app/home/templates/base.html
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

</head>
<style>

	body {
		
		background-color: orange;
		font-family: 'Anton', sans-serif;

	}

	.fixed {
    position: fixed;
    left: 0;
    bottom: 0;
    text-align: center;
    margin:5px;
	}
	
	hr {
    clear: both;
    visibility: hidden;
	}
	a {
		text-decoration; none;
	}
</style>
<h1 style="text-align: center;">ToDo App</h1>

{% block content %}
{% endblock content %}

Programs/toDo_app/home/templates/index.html
{% extends "base.html" %}
{% block content %}

{% for entry in toDo %}
<div class="card text-white bg-warning mb-3" style="max-width: 100rem;">
  <div class="card-body">

  	<a href="delete_todo/{{ entry.id }}">
  		<button type="submit" class="btn btn-danger float-right">DELETE</button>
  	</a>

    <h5 class="card-title">I have to.. ( {{ entry.date_added }} )</h5>
    <p class="card-text">{{ entry }}</p>
 </div>
</div>
{% empty %}
<div class="card text-white bg-warning mb-3" style="max-width: 100rem;">
  <div class="card-body">
    <h5 class="card-title">I have nothing to do!</h5>
  </div>
</div>
{% endfor %}
<hr><hr><hr>
<a href="/new_todo"><button type="button" class="btn btn-primary btn-lg btn-block fixed">ADD</button></a>

{% endblock content %}

Programs/toDo_app/home/templates/new_todo.html
{% extends "base.html" %}

{% block content %}
	<h3 style="text-align: center;">I have to</h3>
	<form action="{% url 'home:new_todo' %}" method="post">
		{% csrf_token %}
		<!--{{ form.as_p }} 
		<p><textarea name="text" id="id_text" required rows="10" cols="40">
				</textarea></p> -->
		<div class="form-group">
    		<textarea name="text" id="id_text" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  		</div>
		<a href="/"><button type="submit" class="btn btn-primary btn-lg btn-block">ADD</button></a>
	</form>

{% endblock content %}